services:
  application-backend:
    image: localhost/backend-image:latest
    ports:
      - "8000:8000"

  application-frontend:
    image: localhost/frontend-image:latest
    ports:
      - "8080:8080"