"""
This file is responsible for calling the functions responsible for calculating expert and transaction signals that are
generated by the application.
"""

from typing import Tuple, Dict

import pandas as pd
import numpy as np

import src.core.strategy_methods as strategy_methods
import src.core.strategy_functions as strategy_functions
import src.core.interpretation_methods as interpretation_methods


def calculate_strategies(data: pd.DataFrame) -> Dict[str, pd.DataFrame | float]:
    """
    This function is responsible for calculating indicators values.
    :param data: data.
    :return: calculated indicators values.
    """
    rsi = strategy_methods.calculate_rsi(data=data, period=14)
    sma_10, sma_10_data = strategy_methods.calculate_sma(data=data, period=10)
    sma_20, sma_20_data = strategy_methods.calculate_sma(data=data, period=20)
    sma_30, sma_30_data = strategy_methods.calculate_sma(data=data, period=30)
    macd_line, macd_signal_line, macd_hist = strategy_methods.calculate_macd(data=data)
    adx, adx_pdi, adx_ndi = strategy_methods.calculate_adx(data=data, period=10)
    bb_upper, bb_lower, bb_std = strategy_methods.calculate_bollinger_bands(
        data=data, period=20
    )

    strategies = {
        "rsi": rsi,
        "sma_10": sma_10,
        "sma_10_data": sma_10_data,
        "sma_20": sma_20,
        "sma_20_data": sma_20_data,
        "sma_30": sma_30,
        "sma_30_data": sma_30_data,
        "macd_line": macd_line,
        "macd_signal_line": macd_signal_line,
        "macd_hist": macd_hist,
        "adx": adx,
        "adx_pdi": adx_pdi,
        "adx_ndi": adx_ndi,
        "bb_upper": bb_upper,
        "bb_lower": bb_lower,
        "bb_std": bb_std
    }
    return strategies


def calculate_signals(data: pd.DataFrame, strategies: Dict) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    This function is responsible for calculate trading signals.
    :param data: data.
    :param strategies: calculated strategies values.
    :return: calculated signals values.
    """
    signals_buy = np.zeros(7)
    signals_sell = np.zeros(7)
    signals_hold = np.zeros(7)

    strategy_functions.calculate_signals_sma(
        sma_n=strategies["sma_10"],
        sma_m=strategies["sma_30"],
        num=0,
        signals_buy=signals_buy,
        signals_sell=signals_sell,
        signals_hold=signals_hold,
    )

    strategy_functions.calculate_signals_rsi(
        rsi=strategies["rsi"].iloc[-1],
        num=1,
        signals_buy=signals_buy,
        signals_sell=signals_sell,
        signals_hold=signals_hold,
    )

    strategy_functions.calculate_signals_bollinger_bands(
        data=data,
        bb_up_line=strategies["bb_upper"].iloc[-1],
        bb_down_line=strategies["bb_lower"].iloc[-1],
        num=2,
        signals_buy=signals_buy,
        signals_sell=signals_sell,
        signals_hold=signals_hold,
    )

    strategy_functions.calculate_signals_macd(
        hist=strategies["macd_hist"],
        num=3,
        signals_buy=signals_buy,
        signals_sell=signals_sell,
        signals_hold=signals_hold,
    )

    strategy_functions.calculate_signals_adx(
        adx=strategies["adx"],
        pdm=strategies["adx_pdi"],
        ndm=strategies["adx_ndi"],
        num=4,
        signals_buy=signals_buy,
        signals_sell=signals_sell,
        signals_hold=signals_hold,
    )

    strategy_functions.calculate_signals_volume(
        data=data,
        num=5,
        signals_buy=signals_buy,
        signals_sell=signals_sell,
        signals_hold=signals_hold,
    )

    signals_buy[6] = signals_buy[5]
    signals_sell[6] = signals_sell[5]
    signals_hold[6] = signals_hold[5]

    return signals_buy, signals_sell, signals_hold


def interpret_strategies_result(
    signals_buy: np.ndarray, signals_sell: np.ndarray, signals_hold: np.ndarray
) -> tuple[str, str, str]:
    """
    This function is responsible for aggregating the results of calculated trading signals.
    :param signals_buy: buy data.
    :param signals_sell: sell data.
    :param signals_hold: hold data.
    :return: calculated signals.
    """
    additive = interpretation_methods.additive_method(
        signals_buy, signals_sell, signals_hold
    )
    majority = interpretation_methods.majority_vote_method(
        signals_buy, signals_sell, signals_hold
    )
    median = interpretation_methods.median_method(
        signals_buy, signals_sell, signals_hold
    )

    additive = "buy" if additive[0] == 1 else "sell" if additive[1] == 1 else "hold"
    majority = "buy" if majority[0] == 1 else "sell" if majority[1] == 1 else "hold"
    median = "buy" if median[0] == 1 else "sell" if median[1] == 1 else "hold"

    return additive, majority, median