"""
This file is responsible for calling the functions responsible for calculating expert and
transaction signals that are generated by the application.
"""

import pandas as pd
import numpy as np
from pandas.api.extensions import ExtensionArray

from src.core import strategy_methods
from src.core import strategy_functions
from src.core import interpretation_methods


def _calculate_strategies_sma(data: pd.DataFrame) -> dict[str, object]:
    """
    This function is responsible for calculating sma indicator value.
    :param data: market data
    :type data: pd.DataFrame
    :return: calculated sma value
    :rtype: dict[str, object]
    """
    sma_10, sma_10_data = strategy_methods.calculate_sma(data=data, period=10)
    sma_20, sma_20_data = strategy_methods.calculate_sma(data=data, period=20)
    sma_30, sma_30_data = strategy_methods.calculate_sma(data=data, period=30)
    sma_strategies = {
        "sma_10": sma_10,
        "sma_10_data": sma_10_data,
        "sma_20": sma_20,
        "sma_20_data": sma_20_data,
        "sma_30": sma_30,
        "sma_30_data": sma_30_data,
    }
    return sma_strategies


def _calculate_strategies_bb(data: pd.DataFrame) -> dict[str, pd.Series]:
    """
    This function is responsible for calculating bb indicator value.
    :param data: market data
    :type data: pd.DataFrame
    :return: calculated bb value
    :rtype: dict[str, object]
    """
    bb_upper, bb_lower, bb_std = strategy_methods.calculate_bollinger_bands(
        data=data, period=20
    )
    bb_strategies = {
        "bb_upper": bb_upper,
        "bb_lower": bb_lower,
        "bb_std": bb_std,
    }
    return bb_strategies


def _calculate_strategies_macd(
    data: pd.DataFrame,
) -> dict[str, pd.Series | np.ndarray[tuple[int], np.dtype] | ExtensionArray]:
    """
    This function is responsible for calculating macd indicator value.
    :param data: market data
    :type data: pd.DataFrame
    :return: calculated macd value
    :rtype: dict[str, object]
    """
    macd_line, macd_signal_line, macd_hist = strategy_methods.calculate_macd(data=data)
    macd_strategies = {
        "macd_line": macd_line,
        "macd_signal_line": macd_signal_line,
        "macd_hist": macd_hist,
    }
    return macd_strategies


def _calculate_strategies_adx(data: pd.DataFrame) -> dict[str, pd.Series]:
    """
    This function is responsible for calculating adx indicator value.
    :param data: market data
    :type data: pd.DataFrame
    :return: calculated adx value
    :rtype: dict[str, object]
    """
    adx, adx_pdi, adx_ndi = strategy_methods.calculate_adx(data=data, period=10)
    adx_strategies = {
        "adx": adx,
        "adx_pdi": adx_pdi,
        "adx_ndi": adx_ndi,
    }
    return adx_strategies


def _calculate_strategies_rsi(data: pd.DataFrame) -> dict[str, pd.Series]:
    """
    This function is responsible for calculating rsi indicator value.
    :param data: market data
    :type data: pd.DataFrame
    :return: calculated rsi value
    :rtype: dict[str, object]
    """
    rsi = strategy_methods.calculate_rsi(data=data, period=14)
    rsi_strategies = {
        "rsi": rsi,
    }
    return rsi_strategies


def calculate_strategies(data: pd.DataFrame) -> dict[str, object]:
    """
    This function is responsible for calculating indicators values.
    :param data: data.
    :return: calculated indicators values.
    """
    strategies: dict[str, object] = {}

    strategies.update(_calculate_strategies_sma(data))
    strategies.update(_calculate_strategies_bb(data))
    strategies.update(_calculate_strategies_macd(data))
    strategies.update(_calculate_strategies_adx(data))
    strategies.update(_calculate_strategies_rsi(data))

    return strategies


def calculate_signals(
    data: pd.DataFrame, strategies: dict
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    This function is responsible for calculate trading signals.
    :param data: data.
    :param strategies: calculated strategies values.
    :return: calculated signals values.
    """
    signals = np.zeros((3, 7))

    strategy_functions.calculate_signals_sma(
        sma_n=strategies["sma_10"], sma_m=strategies["sma_30"], num=0, signals=signals
    )

    strategy_functions.calculate_signals_rsi(
        rsi=strategies["rsi"].iloc[-1], num=1, signals=signals
    )

    strategy_functions.calculate_signals_bollinger_bands(
        data=data,
        bb_up_line=strategies["bb_upper"].iloc[-1],
        bb_down_line=strategies["bb_lower"].iloc[-1],
        num=2,
        signals=signals,
    )

    strategy_functions.calculate_signals_macd(
        hist=strategies["macd_hist"], num=3, signals=signals
    )

    strategy_functions.calculate_signals_adx(
        adx=strategies["adx"],
        pdm=strategies["adx_pdi"],
        ndm=strategies["adx_ndi"],
        num=4,
        signals=signals,
    )

    strategy_functions.calculate_signals_volume(data=data, num=5, signals=signals)

    signals[0, 6] = signals[0, 5]
    signals[1, 6] = signals[1, 5]
    signals[2, 6] = signals[2, 5]

    return signals[0], signals[1], signals[2]


def interpret_strategies_result(
    signals_buy: np.ndarray, signals_sell: np.ndarray, signals_hold: np.ndarray
) -> tuple[str, str, str]:
    """
    This function is responsible for aggregating the results of calculated trading signals.
    :param signals_buy: buy data.
    :param signals_sell: sell data.
    :param signals_hold: hold data.
    :return: calculated signals.
    """
    additive = interpretation_methods.additive_method(
        signals_buy, signals_sell, signals_hold
    )
    majority = interpretation_methods.majority_vote_method(
        signals_buy, signals_sell, signals_hold
    )
    median = interpretation_methods.median_method(
        signals_buy, signals_sell, signals_hold
    )

    additive_conversion = (
        "BUY" if additive[0] == 1 else "SELL" if additive[1] == 1 else "HOLD"
    )
    majority_conversion = (
        "BUY" if majority[0] == 1 else "SELL" if majority[1] == 1 else "HOLD"
    )
    median_conversion = (
        "BUY" if median[0] == 1 else "SELL" if median[1] == 1 else "HOLD"
    )

    return additive_conversion, majority_conversion, median_conversion


def parse_expert_signals(
    signals_buy: np.ndarray, signals_sell: np.ndarray, signals_hold: np.ndarray
) -> dict[str, str]:
    """
    This function is responsible for change numbers into bsh information for expert signals
    :param signals_buy: transaction buy signals
    :type signals_buy: np.ndarray
    :param signals_sell: transaction sell signals
    :type signals_sell: np.ndarray
    :param signals_hold: transaction sell signals
    :type signals_hold: np.ndarray
    :return: bsh signal for expert systems
    :rtype: dict[str, str]
    """
    arrays: np.ndarray = np.array([signals_buy, signals_sell, signals_hold])
    maximum = np.max(arrays, axis=0)
    is_max = arrays == maximum
    signals = np.array(["BUY", "SELL", "HOLD"])
    signals_bsh: tuple[str, ...] = tuple("/".join(signals[col]) for col in is_max.T)
    result: dict[str, str] = {
        "sma": signals_bsh[0],
        "rsi": signals_bsh[1],
        "bb": signals_bsh[2],
        "macd": signals_bsh[3],
        "adx": signals_bsh[4],
        "volume": signals_bsh[5],
    }
    return result
