[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gabriel", email = "gabkomti@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.4",
    "uvicorn[standard]>=0.52.1",
    "websocket-client>=1.9.0",
    "yfinance>=1.5.2",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "black>=26.5.1",
    "flake8>=7.3.0",
    "mypy>=2.3.1",
    "pandas-stubs>=3.0.5.260730",
    "pylint>=4.0.7",
    "pytest>=9.1.1",
]

[[tool.mypy.overrides]]
module = ["yfinance"]
ignore_missing_imports = true
